version = 0.1
[default.deploy.parameters]
stack_name = "inviteUserToProject"
resolve_s3 = true
s3_prefix = "inviteUserToProject"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
