version = 0.1
[default.deploy.parameters]
stack_name = "respondProjectInvitation"
resolve_s3 = true
s3_prefix = "respondProjectInvitation"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
