version = 0.1
[default.deploy.parameters]
stack_name = "galleries-api"
resolve_s3 = true
s3_prefix = "galleries-api"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "StageName=\"dev\""
image_repositories = []
